create extension if not exists pgcrypto;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'reviews'
      and column_name = 'user_id'
      and data_type = 'integer'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'legacy_reviews'
  ) then
    alter table public.reviews rename to legacy_reviews;
  end if;

  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'discussion_replies'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'legacy_discussion_replies'
  ) then
    alter table public.discussion_replies rename to legacy_discussion_replies;
  end if;

  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'discussions'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'legacy_discussions'
  ) then
    alter table public.discussions rename to legacy_discussions;
  end if;

  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'user_books'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'legacy_user_books'
  ) then
    alter table public.user_books rename to legacy_user_books;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'books'
      and column_name = 'created_by'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'legacy_books'
  ) then
    alter table public.books rename to legacy_books;
  end if;

  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'users'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'legacy_users'
  ) then
    alter table public.users rename to legacy_users;
  end if;
end
$$;

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  isbn text unique,
  cover_url text,
  description text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  body text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, book_id)
);

create index if not exists reviews_book_id_idx on public.reviews (book_id, created_at desc);
create index if not exists reviews_user_id_idx on public.reviews (user_id, created_at desc);

create or replace function public.book_rating_summary(target_book_id bigint)
returns table (
  average_rating numeric,
  review_count bigint
)
language sql
stable
as $$
  select
    round(avg(rating)::numeric, 2) as average_rating,
    count(*) as review_count
  from public.reviews
  where book_id = target_book_id;
$$;

alter table public.books enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "Books are viewable by everyone" on public.books;
create policy "Books are viewable by everyone"
on public.books
for select
to anon, authenticated
using (true);

drop policy if exists "Books can be inserted by everyone" on public.books;
create policy "Books can be inserted by everyone"
on public.books
for insert
to anon, authenticated
with check (true);

drop policy if exists "Reviews are viewable by everyone" on public.reviews;
create policy "Reviews are viewable by everyone"
on public.reviews
for select
to anon, authenticated
using (true);

drop policy if exists "Users can create their own reviews" on public.reviews;
create policy "Users can create their own reviews"
on public.reviews
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own reviews" on public.reviews;
create policy "Users can update their own reviews"
on public.reviews
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own reviews" on public.reviews;
create policy "Users can delete their own reviews"
on public.reviews
for delete
to authenticated
using (auth.uid() = user_id);
