create table if not exists public.users (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  avatar text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.books (
  id integer generated by default as identity primary key,
  title text not null,
  author text not null,
  cover_url text,
  created_by integer references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_books (
  user_id integer not null references public.users(id) on delete cascade,
  book_id integer not null references public.books(id) on delete cascade,
  status text not null check (status in ('Reading', 'Completed', 'Want to Read')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, book_id)
);

create table if not exists public.reviews (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  book_id integer not null references public.books(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discussions (
  id integer generated by default as identity primary key,
  book_id integer not null references public.books(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  title text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discussion_replies (
  id integer generated by default as identity primary key,
  discussion_id integer not null references public.discussions(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_created_at_idx on public.books (created_at desc);
create index if not exists reviews_book_id_created_at_idx on public.reviews (book_id, created_at desc);
create index if not exists discussions_book_id_created_at_idx on public.discussions (book_id, created_at desc);
create index if not exists discussion_replies_discussion_id_idx on public.discussion_replies (discussion_id);
create index if not exists user_books_user_id_updated_at_idx on public.user_books (user_id, updated_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists books_set_updated_at on public.books;
create trigger books_set_updated_at
before update on public.books
for each row execute function public.set_updated_at();

drop trigger if exists user_books_set_updated_at on public.user_books;
create trigger user_books_set_updated_at
before update on public.user_books
for each row execute function public.set_updated_at();

drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

drop trigger if exists discussions_set_updated_at on public.discussions;
create trigger discussions_set_updated_at
before update on public.discussions
for each row execute function public.set_updated_at();

drop trigger if exists discussion_replies_set_updated_at on public.discussion_replies;
create trigger discussion_replies_set_updated_at
before update on public.discussion_replies
for each row execute function public.set_updated_at();
